### PR TITLE
Added specifications for date and number formatting

### LINKED ISSUE #30: Add support for date and number formatting
The current `@format` option offers support only for string templates. Similar support would be nice for date and number formatting.

### PR DESCRIPTION
**Pull request by vladbailescu**

### CODE REVIEW

**Comment by paul-bjorkstrand** [comment]
The single quote escape may not be ideal, as most of the examples (and almost all of the code I've written) use single quotes to represent strings within an expression. Thoughts?

**Comment by vladbailescu** [comment]
@paul-bjorkstrand Generally, you can either escape every character individually or surround a block with special escape chars. Since the single quotes are more widely supported (eg: both Java and .NET default formatting utilities support single quotes, double quotes are only supported in .NET) I opted for these.

Strings in expression can also be specified surrounded by double quotes:

`${"'The time is: 'HH:mm" @ format=myDate}`

**Comment by paul-bjorkstrand** [comment]
I understand the motivation. My main reason for for bringing it up was due to many people (at least in my experience) using single quotes for string literals. It is probably for consistency, if anything else, due to using single quotes when inside attributes, e.g. `class="${ifTrue ? 'some-class', ''}"`.

Though it is likely more effort than it's worth, an optional param for date format escape chars (defaulted to `' '`) could help with any confusion stemming from single quotes being used.

Anyway, thanks for the response.

**Comment by raducotescu** [comment]
Applied PR in 3868c621f54e91144084593540f123c15046fae4.

**Pull request closed without merging**
